# Generated by Django 6.0.1 on 2026-01-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], default='General', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.FloatField(default=0.0),
        ),
    ]
