# Generated by Django 6.0.2 on 2026-02-15 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('courses_offered', models.JSONField(default=list)),
                ('annual_fees', models.FloatField(default=0)),
                ('facilities', models.JSONField(default=list)),
                ('cutoff_general', models.FloatField(default=0)),
                ('cutoff_obc', models.FloatField(default=0)),
                ('cutoff_sc', models.FloatField(default=0)),
                ('cutoff_st', models.FloatField(default=0)),
                ('placement_rate', models.FloatField(default=0)),
                ('avg_package', models.FloatField(default=0)),
                ('review_score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('marks', models.FloatField(default=0.0)),
                ('category', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], default='General', max_length=10)),
                ('preferred_courses', models.JSONField(default=list)),
                ('preferred_location', models.CharField(blank=True, max_length=100)),
                ('budget', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_score', models.FloatField(default=0)),
                ('course_score', models.FloatField(default=0)),
                ('location_score', models.FloatField(default=0)),
                ('budget_score', models.FloatField(default=0)),
                ('placement_score', models.FloatField(default=0)),
                ('facility_score', models.FloatField(default=0)),
                ('review_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('star_rating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='recommendations.college')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='recommendations.student')),
            ],
            options={
                'ordering': ['-total_score'],
                'unique_together': {('student', 'college')},
            },
        ),
    ]
