# Generated by Django 6.0.2 on 2026-03-08 12:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('courses_offered', models.TextField(blank=True, default='', help_text='Enter courses separated by commas (e.g., BTech, BSc, MBA)')),
                ('annual_fees', models.FloatField(default=0)),
                ('facilities', models.TextField(blank=True, default='', help_text='Enter facilities separated by commas (e.g., Hostel, Library, Sports, Lab)')),
                ('cutoff_general', models.FloatField(default=0)),
                ('cutoff_obc', models.FloatField(default=0)),
                ('cutoff_sc', models.FloatField(default=0)),
                ('cutoff_st', models.FloatField(default=0)),
                ('placement_rate', models.FloatField(default=0)),
                ('avg_package', models.FloatField(default=0)),
                ('review_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('marks', models.FloatField(default=0.0)),
                ('category', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], default='General', max_length=10)),
                ('preferred_courses', models.TextField(blank=True, default='', help_text='Enter preferred courses separated by commas')),
                ('preferred_location', models.CharField(blank=True, default='', max_length=100)),
                ('budget', models.FloatField(default=0)),
                ('min_rating', models.FloatField(default=3.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recommendations.college')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('college', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0)),
                ('star_rating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='recommendations.college')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='recommendations.student')),
            ],
            options={
                'ordering': ['-total_score'],
                'unique_together': {('student', 'college')},
            },
        ),
    ]
